# Project information
site_name: Financial Research Data Services
site_description: Financial Research Data Services
site_author: Mingze Gao
site_url: https://frds.io/

# Repository
repo_name: mgao6767/frds
repo_url: https://github.com/mgao6767/frds/

# Copyright
copyright: Copyright &copy; 2020-2021 frds.io

# Configuration
theme:
  name: material
  features:
    - tabs
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.expand
    - navigation.top
    - content.code.annotate
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/frds_icon.png
  logo: images/image.png
  custom_dir: overrides

# Plugins
plugins:
  - tags:
      tags_file: measures.md
  - search # necessary for search to work
  - git-revision-date-localized
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True
  - minify:
      minify_html: true
  - mkapi:
      # src_dirs: [frds]
      filters: [strict]

# Extensions
markdown_extensions:
  - meta
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: true
      # noclasses: true
      pygments_style: xcode
      linenums_style: pymdownx-inline
      # linenums: true
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
  - javascripts/extra.js

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  analytics:
    provider: google
    property: UA-114057186-1
  generator: false

nav:
  - Home:
    - FRDS: index.md
    - Getting Started: https://frds.io/getting-started/
    - Documentation: https://frds.io/measures/
  - Getting Started: getting-started.md
  - Measures:
      - Measures: measures.md
      - General:
          - HHI index: measures/hhi_index.md
          - Kyle's lambda: measures/kyle_lambda.md
      - Banking:
          - Absoprtion ratio: measures/absorption_ratio.md
          - Contingent claim analysis: measures/cca.md 
          - Distress insurance premium: measures/distress_insurance_premium.md
          - Marginal expected shortfall: measures/marginal_expected_shortfall.md
          - Systemic expected shortfall: measures/systemic_expected_shortfall.md
          - Z-score: measures/bank_z_score.md
      - Corporate:
          - Book leverage: measures/book_leverage.md
          - Capital expenditure: measures/capital_expenditure.md
          - Firm size: measures/firm_size.md
          - Market-to-book ratio: measures/market_to_book.md
          - ROA: measures/roa.md
          - ROE: measures/roe.md
          - Tangibility: measures/tangibility.md
     

