# Project information
site_name: Financial Research Data Services
site_description: Financial Research Data Services
site_author: Mingze Gao
site_url: https://frds.io/

# Repository
repo_name: mgao6767/frds
repo_url: https://github.com/mgao6767/frds/

# Copyright
copyright: Copyright &copy; 2020-2021 frds.io

google_analytics:
  - UA-114057186-3
  - auto

# Configuration
theme:
  name: material
  features:
    - tabs
    - navigation.tabs
  language: en
  palette:
    primary: white
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/frds_icon.png
  logo: images/frds_icon.png
  custom_dir: overrides

# Plugins
plugins:
  - search # necessary for search to work
  - git-revision-date-localized
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True
  # - minify:
  #     minify_html: true
  - mkapi:
      # src_dirs: [frds]
      filters: [strict]

# Extensions
markdown_extensions:
  - meta
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - javascripts/extra.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css

nav:
  - Introduction: index.ipynb
  - Getting Started: getting-started.ipynb
  # - Measures Supported: measures.md
  - Measures:
      - Measures: measures.md
      - Corporate:
          - Book leverage: measures/book_leverage.md
          - Capital expenditure: measures/capital_expenditure.md
          - Firm size: measures/firm_size.md
          - Market-to-book ratio: measures/market_to_book.md
          - ROA: measures/roa.md
          #     - Accounting Restatement: measures/accounting_restatement.md
          #     - Credit Rating: measures/credit_rating.md
          #     - Executive Ownership: measures/executive_ownership.md
          - ROE: measures/roe.md
          - Tangibility: measures/tangibility.md
  #     - Stock Delisting: measures/stock_delisting.md
  #     - Tobin's Q: measures/tobin_q.md
  #     - BHC Size: measures/bhc_size.md
  #     - BHC Loan Growth: measures/bhc_loan_growth.md
  #     - BHC FX Exposure: measures/bhc_fx_exposure.md
  #     - BHC NetIncome/Assets: measures/bhc_netincome_to_assets.md
  #     - BHC Dividend/Assets: measures/bhc_dividend_to_assets.md
  #     - BHC RegulatoryCapital/Assets: measures/bhc_regcap_to_assets.md
  #     - BHC Tier1Capital/Assets: measures/bhc_tier1cap_to_assets.md
  #     - BHC Gross IR Hedging: measures/bhc_gross_ir_hedging.md
  #     - BHC Gross FX Hedging: measures/bhc_gross_fx_hedging.md
  #     - BHC Maturity Gap: measures/bhc_maturity_gap.md
  # - API: mkapi/api/frds/measures
