# Project information
site_name: Financial Research Data Services
site_description: Financial Research Data Services
site_author: Mingze Gao
site_url: https://frds.io/

# Repository
repo_name: mgao6767/frds
repo_url: https://github.com/mgao6767/frds/

# Copyright
copyright: Copyright &copy; 2020 frds.io

# Configuration
theme:
  name: material
  features:
    - tabs
  language: en
  palette:
    primary: white
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/frds_icon.png
  logo: images/frds_icon.png
  # custom_dir: overrides

# Plugins
plugins:
  - search # necessary for search to work
  - git-revision-date-localized
  # - minify:
  #     minify_html: true
  # - mkapi

# Extensions
markdown_extensions:
  - meta
  - admonition
  - footnotes
  - codehilite:
      linenums: true
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

extra_javascript:
- javascripts/extra.js
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

nav:
- Home: index.md
- Getting Started: 
  - Installation: getting-started.md
  - Setup: setup.md
  - Usage: usage.md
- Measures Supported: measures.md
- Measures Documentation:
  - Accounting Restatement: measures/accounting_restatement.md
  - Asset Tangibility: measures/asset_tangibility.md
  - Book Leverage: measures/book_leverage.md
  - Capital Expenditure: measures/capital_expenditure.md
  - Executive Ownership: measures/executive_ownership.md
  - Firm Size: measures/firm_size.md
  - Market to Book: measures/market_to_book.md
  - ROA: measures/roa.md
  - ROE: measures/roe.md
  - BHC Size: measures/bhc_size.md
  - BHC FX Exposure: measures/bhc_fx_exposure.md
  - BHC NetIncome/Assets: measures/bhc_netincome_to_assets.md
  - BHC Dividend/Assets: measures/bhc_dividend_to_assets.md
  - BHC RegulatoryCapital/Assets: measures/bhc_regcap_to_assets.md
  - BHC Tier1Capital/Assets: measures/bhc_tier1cap_to_assets.md
  - BHC Gross IR Hedging: measures/bhc_gross_ir_hedging.md
  - BHC Gross FX Hedging: measures/bhc_gross_fx_hedging.md