name: Build and Deploy Docs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          python -m pip install --upgrade pip
          pip install git+https://${{ secrets.GH_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
          pip install mkdocs-git-revision-date-localized-plugin mkdocs-jupyter mkapi mkdocs-minify-plugin
          pip install -r requirements.txt
          python setup.py build_ext --inplace
          pip install -e .
      - run: mkdocs gh-deploy --force
